# Generated by Django 2.0 on 2017-12-03 08:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clss',
            fields=[
                ('classId', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('className', models.CharField(max_length=20)),
                ('classClass', models.CharField(max_length=20)),
                ('classAcademy', models.CharField(max_length=30)),
                ('classCredit', models.IntegerField()),
                ('classCapacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentCallRate', models.IntegerField()),
                ('commentPassRate', models.IntegerField()),
                ('commentGetRate', models.IntegerField()),
                ('commentDetail', models.TextField(max_length=300)),
                ('commentCommitTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('commentIfPass', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseOnlyId', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('courseLikes', models.IntegerField(default=0)),
                ('courseUnlikes', models.IntegerField(default=0)),
                ('courseCommentNum', models.IntegerField(default=0)),
                ('courseCallRate', models.IntegerField(default=0)),
                ('coursePassRate', models.IntegerField(default=0)),
                ('courseGetRate', models.IntegerField(default=0)),
                ('courseLastRate', models.IntegerField(default=5)),
                ('clss', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='hbue.Clss')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='hbue.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherId', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('teacherName', models.CharField(max_length=20)),
                ('teacherIcon', models.CharField(max_length=30)),
                ('teacherInfo', models.TextField(max_length=300)),
                ('clss', models.ManyToManyField(through='hbue.Course', to='hbue.Clss')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('userName', models.CharField(max_length=20)),
                ('userPassword', models.CharField(max_length=20)),
                ('userEmail', models.CharField(max_length=30)),
                ('userPhone', models.CharField(max_length=11)),
                ('userIcon', models.CharField(default='user.png', max_length=20)),
                ('userInfo', models.CharField(default='', max_length=300)),
                ('userAcademy', models.CharField(max_length=20)),
                ('userLevel', models.IntegerField(default=1)),
                ('course', models.ManyToManyField(through='hbue.Comment', to='hbue.Course')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='hbue.User'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='hbue.Teacher'),
        ),
        migrations.AddField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='hbue.Course'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='hbue.User'),
        ),
    ]
